// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package folder

import (
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func Wire(log *logrus.Logger) *controller {
	folderService := ProvideService(log)
	folderController := ProvideController(folderService)
	return folderController
}
