basePath: /api/v1
definitions:
  domain.Folder:
    description: Папка
    properties:
      id:
        description: Идентификатор
        example: 9b4dc8d9-6da7-40c5-b7b1-30e81edca64d
        type: string
      name:
        description: Название
        example: folder name
        type: string
    type: object
  helper.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
host: localhost:5001
info:
  contact: {}
  description: Данное API реализует функции управления паролями.
  license:
    name: GNU GPL v3.0
    url: https://www.gnu.org/licenses/gpl-3.0.html
  title: PassBox API 1.0.
  version: "1.0"
paths:
  /folders/:
    get:
      consumes:
      - application/json
      description: Предоставляет список папок
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Folder'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.HTTPError'
      summary: Список папок
      tags:
      - folders
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
